<?php

namespace ADMIN\ACLBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriasRepository extends EntityRepository
{
}
